name: Build project

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Setup Node.js âš™ï¸
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Skip Scripts Install ğŸ“¦
        run: npm i --skip-scripts  --loglevel=info

      - name: Install cross-fetch ğŸ“¦
        run: npm i cross-fetch  --loglevel=info

      - name: Install dependencies ğŸ“¦
        run: npm i  --loglevel=info

      - name: Zip entire project ğŸ“¦
        shell: pwsh
        run: Compress-Archive -Path * -DestinationPath entire-project.zip

      - name: Upload entire project artifact ğŸ“¤
        uses: actions/upload-artifact@v4
        with:
          name: entire-project
          path: entire-project.zip
